// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAeajTOAgF2ZKv1JgA6EXmwBIYjr1ApdQ',
    appId: '1:722916662508:web:c02aedcf2819cf47b899c9',
    messagingSenderId: '722916662508',
    projectId: 'snapwisefinal',
    authDomain: 'snapwisefinal.firebaseapp.com',
    storageBucket: 'snapwisefinal.firebasestorage.app',
    measurementId: 'G-C9RK9CXXGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChRuxv25stbvN4jG4-aaL_Se8llWgUlOw',
    appId: '1:722916662508:android:4c3f72d175f98132b899c9',
    messagingSenderId: '722916662508',
    projectId: 'snapwisefinal',
    storageBucket: 'snapwisefinal.firebasestorage.app',
  );
}
